/* empty css                      */import{S as a,N as h}from"./assets/vendor-Sm41FR0M.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m=[{selector:".ship-swiper",slideClass:"ship-swiper-slide",wrapperClass:"ship-swiper-wrapper"},{selector:".reviews-swiper",slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper"},{selector:".gallery-swiper",slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",navigation:{nextEl:".gallery-nav .custom-next",prevEl:".gallery-nav .custom-prev"}}],l={};function d(){const i=window.innerWidth;m.forEach(s=>{const o=document.querySelector(s.selector);if(!o)return;const r=s.selector;if(l[r]&&(l[r].destroy(!0,!0),delete l[r]),s.selector===".ship-swiper"){if(i<1439){const e=new a(o,{slidesPerView:1.1,spaceBetween:10,loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal"});l[r]=e}}else if(s.selector===".reviews-swiper"){if(i<1439){const e=new a(o,{slidesPerView:1,spaceBetween:20,loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal"});l[r]=e}}else if(s.selector===".gallery-swiper"){const e=i<374?1.1:i<1439?1.7:6,t=new a(o,{modules:[h],slidesPerView:e,spaceBetween:20,loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal",navigation:s.navigation});l[r]=t}})}document.addEventListener("DOMContentLoaded",d);window.addEventListener("resize",()=>{clearTimeout(window._swiperResizeTimeout),window._swiperResizeTimeout=setTimeout(d,300)});document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),s=i.querySelector(".icon"),o=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const n=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="#D0EFFF" />
</svg>
    `,p=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#D0EFFF" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,s.innerHTML=t?p:n,t?u():c()}),r.forEach(f=>f.addEventListener("click",()=>{c(),s.innerHTML=n,t=!1})),window.addEventListener("scroll",w);function u(){o.style.display="block"}function c(){o.style.display="none"}function w(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const r=document.getElementById("site-header");return r?r.offsetHeight:0}function s(r){const e=document.getElementById(r);if(!e)return;const t=i(),n=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:n,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(r=>{r.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const n=t.substring(1);s(n)})});const o=window.location.hash;if(o){const r=o.substring(1);setTimeout(()=>{s(r)},1e3)}});
//# sourceMappingURL=index.js.map
